---
# Run with ansible-playbook <filename> -k
# make sure to add IPaddress of machines you want to manage to /etc/ansible/hosts first
#
#  Make sure to run the pb-init.yml file before running any other playbooks.
#  It will install all dependencies 
#
#  By: 
#  _____ _          _     _              _                 _____                  
# /  __ \ |        (_)   | |            | |               |  __ \                  ®
# | /  \/ |__  _ __ _ ___| |_ ___  _ __ | |__   ___ _ __  | |  \/_ __ __ _ _   _  
# | |   | '_ \| '__| / __| __/ _ \| '_ \| '_ \ / _ \ '__| | | __| '__/ _` | | | | 
# | \__/\ | | | |  | \__ \ || (_) | |_) | | | |  __/ |    | |_\ \ | | (_| | |_| | 
#  \____/_| |_|_|  |_|___/\__\___/| .__/|_| |_|\___|_|     \____/_|  \__,_|\__, | 
#                                 | |                                       __/ | 
#                                 |_|                                      |___/  
#  https://github.com/c2theg
#  Copyright (c) 2001-2018
# 
#
#    Version: 0.0.1
#    Updated: 8/15/18

- hosts: all
  gather_facts: False
  remote_user: ubuntu
  become: yes
  become_user: root
  become_method: sudo

  vars:
    # used for filepaths
    site_name: "chrisgray"
    # used in the website's markup
    site_title: "Hope"
    # used in the web server config file
    site_url: "www.github.com"


  tasks:
    - name: Install Nginx
      package: name=nginx state=latest

    - name: Create website directory
      file: path="/var/www/{{ site_name }}" state=directory " state=directory mode=0755

    - name: Create main nginx config file
      template:
        src: "template/nginx.conf"
        dest: "/etc/nginx/nginx.conf"
      notify:
      - restart nginx

    - name: Create nginx vhost config file
      template:
         src: "template/website.conf"
         dest: "/etc/nginx/conf.d/{{ site_name }}.conf"
      notify:
      - restart nginx

    - name: Create website
      template:
        src: "templates/index.html"
        dest: "/var/www/{{ site_name }}/index.html"

    - name: Remove default nginx vhost configuration
      file: path=/etc/nginx/sites-enabled/default state-absent
      notify:
      - restart nginx

  handlers:
    - name: restart nginx
      service:
          name: nginx
          state: restarted
