#  Docker compose file which creates a ElasticSearch container
#  By: Christopher MJ Gray
#  version: 0.0.2
#  10/3/18
#  Source: https://raw.githubusercontent.com/c2theg/srvBuilds/master/docker/compose-configs/docker-compose_elastic-kibana.yml
#  References: https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
#              https://www.docker.elastic.co/
#---------------------------------------------------------------------------------------------------------------------------
version: '3.6'

services:
# =================
# = ElasticSearch =
# =================
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
        memlock:
            soft: -1
            hard: -1
    secrets:
      - source: ca.crt
        target: /usr/share/elasticsearch/config/certs/ca/ca.crt
      - source: elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
      - source: elasticsearch.keystore
        target: /usr/share/elasticsearch/config/elasticsearch.keystore
      - source: elasticsearch.key
        target: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.key
      - source: elasticsearch.crt
        target: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.crt
    ports: ['9200:9200']
    networks: ['esnet']
    volumes:
      - 'es_data:/usr/share/elasticsearch/data'
      - './scripts/setup-users.sh:/usr/local/bin/setup-users.sh:ro'
      - ./custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    healthcheck:
#      test: curl --cacert /usr/share/elasticsearch/config/certs/ca/ca.crt -s https://localhost:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5
      
# =================
# =    Kibana     =
# =================
  kibana:
    container_name: kibana
    image: kibana
    ports:
        - 5601:5601
    volumes:
        - ./custom_elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
#    environment:
           
#-------------------------------------------------------------------        
volumes:
  es_data:
    driver: local
    
networks:
  esnet:
