#  Docker compose file which creates a Nginx & PHP container, and sets resource limits
#  By: Christopher MJ Gray
#  version: 0.1.1
#  10/2/18
#  Source: https://raw.githubusercontent.com/c2theg/srvBuilds/master/docker/compose-configs/docker-compose-nginx_php.yml
#
#---------------------------------------------------------------------------------------------------------------------------
version: '3'
services:
# ==============
# =   NGINX    =
# ==============
    web:
        container_name: nginx_site1
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - /media/data/containers/nginx/container-nginx.conf:/etc/nginx/nginx.conf:ro
            - /media/data/containers/nginx/container-site1.conf:/etc/nginx/conf.d/default.conf:ro
            - /media/data/containers/websites/code1:/code:ro
        networks:
            - code-network

# ==============
# =    PHP     =
# ==============
    php:
        container_name: php_latest_prod
        image: php:fpm
        volumes:
            - /media/data/containers/nginx/container-php-fpm.ini:/usr/local/etc/php/php.ini:ro
            - /media/data/containers/websites/code1:/code:ro
        networks:
            - code-network         
#***************************************************************************
networks:
    code-network:
        driver: bridge
