#  Docker compose file which creates a redis container, and sets resource limits
#  By: Christopher MJ Gray
#  version: 0.0.11
#  11/24/18
#  Source: https://raw.githubusercontent.com/c2theg/srvBuilds/master/docker/compose-configs/docker-compose-redis.yml
#          https://docs.docksal.io/tools/redis/

version: '3'
services:
    redis:
        container_name: redis-server1
        image: redis:latest
#        user: '1001'
#        restart: on-failure
#        security_opt:
#            -  apparmor=unconfined
        ports:
            - 46379:46379
        volumes:
            - ./container-redis.conf:/usr/local/etc/redis/redis_46379.conf
#            - "./redis-init.sh:/usr/local/etc/redis/redis-init.sh"
            - /media/data/containers/redis1/data:/data
        command:
            - /usr/local/etc/redis/redis_46379.conf
#            - redis-init.sh
#        env_file:
#            - ./env/.dev.env
#        environment:
#            - REDIS_MAXMEMORY=256m
#            - REDIS_PASSWORD=P@ssw0rd123!
#            - REDIS_LOGFILE=/var/log/redis.log
#        privileged: true
#        sysctls:
#            net.core.somaxcomm: '511'
#            --tcp-backlog 128
#            - slaveof 10.0.0.2 6379
#            - requirepass secret 
#        network_mode: "host"
