#  Docker compose file which creates a ElasticSearch container
#  By: Christopher MJ Gray
#  version: 0.0.1
#  10/3/18
#  Source:
#
#---------------------------------------------------------------------------------------------------------------------------
version: '3.1'

services:
# =================
# = ElasticSearch =
# =================
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    ports:
        - 9200:9200
    volumes:
#            - ./container-memcached.conf:/usr/local/etc/memcached/memcached.conf:ro
        - esdata1:/usr/share/elasticsearch/data
    environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        - "discovery.zen.ping.unicast.hosts=elasticsearch"
    ulimits:
        memlock:
            soft: -1
            hard: -1
    networks:
        - esnet

# =================
# =    Kibana     =
# =================
  kibana:
    container_name: kibana
    image: kibana
    ports:
      - 5601:5601
#       volumes:
#            - ./container-memcached.conf:/usr/local/etc/memcached/memcached.conf:ro
        environment:
            - MEMCACHED_CACHE_SIZE=128
            
#-------------------------------------------------------------------        
volumes:
  esdata1:
    driver: local
    
networks:
  esnet:
