#  Docker compose file which creates a MongoDB container
#  By: Christopher MJ Gray
#  version: 0.0.1
#  10/3/18
#  Source: https://raw.githubusercontent.com/c2theg/srvBuilds/master/docker/compose-configs/docker-compose-mongodb.yml
#
#---------------------------------------------------------------------------------------------------------------------------
version: '3'
services:
# ==============
# =  MongoDB   =
# ==============
    mongodb:
        image: mongo:latest
        container_name: "mongodb"
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/var/log/mongodb
            - ALLOW_EMPTY_PASSWORD=yes
            - MONGODB_EXTRA_FLAGS=--wiredTigerCacheSizeGB=2
        volumes:
            - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null # --quiet
        networks:
            - app-tier


networks:
  app-tier:
    driver: bridge
