#   By: Chris Gray
#   Version 0.0.28
#   Updated: 4/28/2025
#
#   Path:
#       /media/frigate/config/config.yaml
#
#   Source:
#       https://docs.frigate.video/configuration/#common-configuration-examples
#       https://docs.frigate.video/configuration/cameras
#       https://docs.frigate.video/configuration/camera_specific/
#       https://docs.frigate.video/configuration/object_detectors/
#       https://docs.frigate.video/configuration/review
#       https://docs.frigate.video/configuration/genai
#-------------------------------------------------------------------------

mqtt:
  enabled: False
  #host: 192.168.X.X # <---- same mqtt broker that home assistant uses
  #host: core-mosquitto
  #user: mqtt-user
  #password: xxxxxxxxxx


ffmpeg:
  hwaccel_args: preset-vaapi         # Intel MiniPC
#  hwaccel_args: preset-rpi-64-h264  # <-- Raspberry Pi


detectors:
  coral:
    type: edgetpu
    device: usb
#  ov:
#    type: openvino
#    device: AUTO

# model:
#   width: 300
#   height: 300
#   input_tensor: nhwc
#   input_pixel_format: bgr
#   path: /openvino-model/ssdlite_mobilenet_v2.xml
#   labelmap_path: /openvino-model/coco_91cl_bkgr.txt


# default threshold value
motion:
  # Optional: The threshold passed to cv2.threshold to determine if a pixel is different enough to be counted as motion. (default: shown below)
  # Increasing this value will make motion detection less sensitive and decreasing it will make motion detection more sensitive.
  # The value should be between 1 and 255.
  threshold: 30

  #--- contour_area ---
  # Optional: Minimum size in pixels in the resized motion image that counts as motion (default: shown below)
  # Increasing this value will prevent smaller areas of motion from being detected. Decreasing will
  # make motion detection more sensitive to smaller moving objects.
  # As a rule of thumb:
  #  - 10 - high sensitivity
  #  - 30 - medium sensitivity
  #  - 50 - low sensitivity
  contour_area: 50


  #--- Tuning For Large Changes In Motion ---
  # Optional: The percentage of the image used to detect lightning or other substantial changes where motion detection
  #           needs to recalibrate. (default: shown below)
  # Increasing this value will make motion detection more likely to consider lightning or ir mode changes as valid motion.
  # Decreasing this value will make motion detection more likely to ignore large amounts of motion such as a person approaching
  # a doorbell camera.
  lightning_threshold: 0.8


live:
  #width: 1920 # <--- NOT ALLOWED SO DONT ADD IT!
  height: 1080
  quality: 8


detect:
  enabled: true
  width: 1920
  height: 1080
  fps: 5


review:
  detections:
    labels:
      - car
      - cat
      - dog
      - person
      - speech

  alerts:
    labels:
      - car
      - cat
      - dog
      - person
      - speech


objects:
  track:
    - car
    - cat
    - dog
    - person
#    - speech


record:
  enabled: True
  retain:
    days: 3
    mode: motion
  alerts:
    retain:
      days: 7       # <- number of days to keep alert recordings
      mode: motion
  detections:
    retain:
      days: 7       # <- number of days to keep detections recordings
      mode: motion
    pre_capture: 5
    post_capture: 5


snapshots:
  enabled: True
  retain:
    default: 30


birdseye:
  enabled: True
  width: 1920
  height: 1080
  quality: 5
  mode: continuous


#ffmpeg:
#  global_args: -hide_banner -loglevel warning -threads 2


semantic_search:
  enabled: true
  reindex: false
  model_size: small

#---------- Cameras ---------------------------------------------------------------
cameras:
  driveway_cam: # <------ Name the camera
    enabled: True
    ffmpeg:
      inputs:
#        - path: rtsp://192.168.1.10:554/rtsp # <----- The stream you want to use for detection
        - path: rtsp://USERNAME:PASSWORD@192.168.1.10:554/cam/realmonitor?channel=1&subtype=1 # higher end cameras support a third stream with a mid resolution (1280x720, 1920x1080) # <----- Add stream you want to record from
          roles:
            - detect

        - path: rtsp://USERNAME:PASSWORD@192.168.1.10:554/cam/realmonitor?channel=1&subtype=1 # higher end cameras support a third stream with a mid resolution (1280x720, 1920x1080) # <----- Add stream you want to record from
          roles:
            - record

    record: # <----- Enable recording
      enabled: True

#---------- Camera Groups ---------------------------------------------------------------
camera_groups:
  front:
    cameras:
      - driveway_cam
#      - garage_cam
    icon: LuCar
    order: 0
