# Christopher Gray - 6/4/2020
#   
# Source: https://netplan.io/examples
#
# 1) to view interface use:
#       ip a
#    Examples include: ens160 (VMWare), enp0s3, etc.
# 2) cd /etc/netplan/
# 3) sudo nano 01-netcfg.yaml
#     - NO TABS ALLOWED
# 4) save file
# 5) netplan apply
# 6) ping 1.1.1.1
#
# renderer: "networkd" or "NetworkManager"
#
# DEBUG: sudo netplan --debug apply
#--------------------------------------------------------
network:
  version: 2
  renderer: networkd
  ethernets:
    ens160:
     dhcp4: no
     addresses: [192.168.1.20/24]
     gateway4: 192.168.1.1
     nameservers:
       addresses: [9.9.9.9,208.67.222.222,1.1.1.2,8.8.8.8]
