# Christopher Gray - 9/25/2022
#
#   Cloudflare Family Sheild, OpenDNS Family - (Servers dont need to access porn! HA)
#     Both IPv4 and IPv6
#
#  Install:
#     wget https://raw.githubusercontent.com/c2theg/srvBuilds/master/configs/01-network-manager-all.yaml && mv 01-network-manager-all.yaml /etc/netplan/01-network-manager-all.yaml
#     cd /etc/netplan/
#
#
#  nmcli
#  nmcli con show
#  nmcli device show
#  nmcli connection show
# 
#  sudo nmcli con mod 'Wired connection 1' ipv4.addr 10.1.1.30/24 gw4 10.1.1.1 ipv4.dns 10.1.1.1,1.1.1.3,1.0.0.3,208.67.222.222,208.67.220.220
# -------------------------------------------------------
# Let NetworkManager manage all devices on this system
network:
  version: 2
  renderer: NetworkManager
