# Christopher Gray - 12/1/2022
#
#   Cloudflare Family Sheild, OpenDNS Family - (Servers dont need to access porn! HA)
#     Both IPv4 and IPv6
#
#  Install:
#     wget https://raw.githubusercontent.com/c2theg/srvBuilds/master/configs/01-netcfg.yaml && mv 01-netcfg.yaml /etc/netplan/00-installer-config.yaml
#     cd /etc/netplan/
#
# -------------------------------------------------------
# Source: https://netplan.io/examples
#
# 1) to view interface use:
#       ip a
#    Examples include: ens160 (VMWare), enp0s3, etc.
# 2) cd /etc/netplan/
# 3) sudo nano 01-netcfg.yaml
#     - NO TABS ALLOWED
# 4) save file
# 5) netplan apply
# 6) ping 1.1.1.1
# 7) ping google.com
#
#
# renderer: "networkd" or "NetworkManager"
#
# DEBUG: sudo netplan --debug apply
# -------------------------------------------------------
network:
  version: 2
  renderer: networkd
  ethernets:
    ens160:
     dhcp4: yes
#     addresses: [192.168.1.20/24]
#     routes:
#      - to: default
#        via: 192.168.1.1
     nameservers:
       addresses: [208.67.222.123,1.1.1.3,9.9.9.9,2606:4700:4700::1113,2620:119:35::123,2620:fe::fe]
