# Christopher Gray - 5/11/2020
#
# Source: https://netplan.io/examples
#
# 1) to view interface use:
#       ip a
#    Examples include: ens160 (VMWare), enp0s3, etc.
# 2) Create this file: nano /etc/netplan/01-netcfg.yaml
# 3) save file
# 4) netplan apply
# 5) ping 1.1.1.1

# renderer: "networkd" or "NetworkManager"
#--------------------------------------------------------
network:
 version: 2
 renderer: networkd
 ethernets:
  enp1s0f0:
    dhcp4: false
    dhcp6: false
  enp1s0f1:
    dhcp4: false
    dhcp6: false
 bonds:
  bond0:
   dhcp4: false
   dhcp6: false
   interfaces:
     - enp1s0f0
     - enp1s0f1
   addresses: [192.168.3.250/24]
   gateway4: 192.168.3.1
   parameters:
     mode: 802.3ad
   nameservers:
     addresses: [8.8.8.8,8.8.4.4]
