# ======== Christopher Gray - ES v7.6+ - Custom Config v0.6.8 - 3/15/20 ========
# https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html
#   Set Permissions:
#       sudo chmod -R 755 /media/data/es/ && sudo chown -R elasticsearch:elasticsearch /media/data/es/
# ---------------------------------- Cluster -----------------------------------
cluster.name: es_cluster1
#---- unrem the following only if running es in a cluster, OR ES wont work ----
#cluster.routing.allocation.awareness.attributes: rack_id,zone
#cluster.routing.allocation.awareness.force.zone.values: zone1
#cluster.routing.allocation.enable: all
#cluster.routing.allocation.allow_rebalance: always
# ------------------------------------ Node ------------------------------------
node.name: db_1
#node.name: ${HOSTNAME}
node.attr.rack: r1
#node.zone: mobile
node.master: true
node.data: true
node.ingest: true
#search.remote.connect: false
# ---------------------------------- Network -----------------------------------
network.host: localhost
# HAS to be set the same as Kibana for it to work
#network.host: ${ES_NETWORK_HOST} #-- Use Env variable --
http.port: 9200   # incoming HTTP requests
#network.tcp.send_buffer_size: 2048
#network.tcp.receive_buffer_size: 2048
# ----------------------------------- Paths ------------------------------------
path.data: /media/data/es/data
path.logs: /media/data/es/logs
# ----------------------------------- Memory -----------------------------------
bootstrap.memory_lock: false
# --------------------------------- Discovery ----------------------------------
#discovery.seed_hosts: ["127.0.0.1", "[::1]"]
#cluster.initial_master_nodes: ["node-1"]
# ---------------------------------- Gateway -----------------------------------
#gateway.recover_after_nodes: 2
# ---------------------------------- HTTP -----------------------------------
#http.compression_level: 3
#http.cors.allow-origin: "*"
#http.cors.enabled: true
#http.cors.allow-origin: /https?:\/\/localhost(:[0-9]+)?/
#--- if using XPack ---
#http.cors.allow-credentials: true
#http.cors.allow-headers: X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization
#--------------------------------
xpack.security.enabled: false
action.auto_create_index: ".security*,.monitoring*,.watches,.triggered_watches,.watcher-history*,.ml*,.logstats*"
# ----------------------------------- Plugins ------------------------------------
#Default Path: /usr/share/elasticsearch/plugins
#plugin.mandatory: analysis-icu,lang-js
#-- XPack --
#node.ml: true 
#xpack.ml.enabled: true
