#  By: Christopher Gray  |  Updated: 5/25/2026  |  Version 0.0.12  | https://github.com/c2theg
#	 Purpose: To staticly assign an ipv4 address to an interface with vlans
#	 For: Ubuntu 26.04 Server (LTS)
#
#  Quick Download: 
#     curl -fsSL https://raw.githubusercontent.com/c2theg/srvBuilds/refs/heads/master/configs/netplan-2604-vlans.yaml -o netplan-2604-vlans.yaml && sudo chmod 600 netplan-2604-vlans.yaml
#     mv netplan-2604-vlans.yaml /etc/netplan/netplan-2604-vlans.yaml
#     cd /etc/netplan/
# -------------------------------------------------------
#	1) First identify the interface name (like ens33, eth0, enp0s3,  eno4 (Dell Servers), ens160 (VMWare), enp0s3, etc.).
#		 ip a
#	2) ls /etc/netplan/
#
#	3) Override the config with bellow
#		sudo nano netplan-2604-vlans.yaml
#		- save and close
#
# 4) TEST THE PLAN BEFORE DEPLOYING!!!! ***
#    sudo netplan try
#   ** if it all works, then continue **
#
#	5) Apply Settings
#		sudo netplan apply
#
#	6) ping 1.1.1.1
#	7) ping t.co
#
# -------------------------------------------------------
#   NextDNS, Cloudflare Family Sheild (backups), OpenDNS Family - (Servers dont need to access porn!)
#       45.90.30.148, 45.90.28.148, 2a07:a8c0::b5:c827, 208.67.222.123, 1.0.0.3, 9.9.9.9, 2606:4700:4700::1003, 2620:119:35::123, 2620:fe::fe
# 
#   List of Non-Security Focused DNS Providers:
#       208.67.222.222, 1.1.1.1, 8.8.8.8, 2001:4860:4860::8888, 2620:0:ccc::2, 2606:4700:4700::1111
#
# -------------------------------------------------------
#  Source: https://netplan.io/examples
#
#  renderer: "networkd" or "NetworkManager"
#
#  DEBUGGING
#    sudo netplan --debug apply
#      or
#    sudo netplan try
#
#  if you get error: ' Permissions for /etc/netplan/netplan-2604-vlans.yaml are too open. Netplan configuration should NOT be accessible by others.' 
#     sudo chmod 600 /etc/netplan/netplan-2604-vlans.yaml
#
#	 If you get the error "inconsistant indentation"
#		  sed 's/ /./g' 50-cloud-init.yaml
#
# -------------------------------------------------------
network:
  version: 2
  wifis: {}
  # renderer: networkd
  ethernets:
  # ens160: # VMWARE
  # eno4:
    enp193s0:
      set-name: enp193s0
      dhcp6: true
      dhcp4: false
      nameservers:
        addresses: [10.50.1.1, 45.90.30.148, 1.0.0.3, 208.67.222.123, 9.9.9.9, 2606:4700:4700::1003, 2620:119:35::123, 2620:fe::fe, 1.0.0.2]
      match:
        macaddress: 78:55:36:08:f2:d6
    #enp197s0:
    #  accept-ra: true
  vlans:
      vlan200:
        id: 200
        link: enp193s0
        addresses:
          - 10.50.1.10/24
        routes:
          - to: default
            via: 10.50.1.1


#------ stock settings ------------------------------
# This is the network config written by 'subiquity'
# network:
#   ethernets:
#     enp193s0:
#       dhcp4: true
#       dhcp6: true
#       match:
#         macaddress: 78:55:36:08:f2:d6
#       set-name: enp193s0
#     enp197s0:
#       accept-ra: true
#   version: 2
#   wifis: {}
